# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  format:
    desc: Format code
    cmds:
      - uv run ruff check --select I --fix # sorts imports
      - uv run ruff format src/ tests/ tests_extras/ 
      - uv run ruff check src/ tests/ tests_extras/ --fix

  lint:
    desc: lint and type-check
    cmds:
      - uv run ruff check --select I src/
      - uv run ruff format --check src/
      - uv run ruff check src/
      - uv run mypy src/

  # TODO remove this and alter CI job once type checks are running
  lint-slim:
    desc: lint and type-check
    cmds:
      - uv run ruff check --select I src/
      - uv run ruff format --check src/
      - uv run ruff check src/

  test-unit:
    desc: Runs tests
    cmds:
      - uv run --active --all-extras pytest tests/unit/

  test-integration:
    desc: Runs tests
    cmds:
      - uv run --active --all-extras pytest tests/integration/ --backend pandas
      - uv run --active --all-extras pytest tests/integration/ --backend polars
      - uv run --active --all-extras pytest tests/integration/ --backend modin
      - uv run --active --all-extras pytest tests/integration/ --backend dask
      - uv run --active --all-extras pytest tests/integration/ --backend ray
      - uv run --active --all-extras pytest tests/integration/ --backend pyspark

  test:
    desc: Runs tests
    cmds:
      - task test-unit && task test-integration
    
  coverage:
    desc: Runs tests with coverage
    cmds:
      - uv run --active --all-extras coverage run -m pytest tests/ -v
      - uv run --active --all-extras coverage html --omit "tests/**/*"

  docs:
    desc: locally build and serve MkDocs
    cmds:
      - uv run zensical serve